# Generated by Django 2.2.5 on 2020-05-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixels',
            name='color',
            field=models.CharField(max_length=100),
        ),
    ]
