# Generated by Django 2.2.5 on 2020-05-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixels',
            name='colors',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
