# Generated by Django 2.2.5 on 2020-05-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_pixels_colors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RemoveField(
            model_name='pixels',
            name='colors',
        ),
    ]
